/*
Copyright (c) 2023 - 2025 Americus Maximus

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#include "Graphics.Basic.hxx"
#include "RendererValues.hxx"

using namespace Images;
using namespace Renderer;
using namespace RendererModule;

namespace RendererModuleValues
{
    u32 RendererFogState = RENDERER_MODULE_FOG_ACTIVE_LINEAR;
    u32 RendererFogColor = DEFAULT_FOG_COLOR;
    f32 RendererFogDensity;
    f32 RendererFogStart;
    f32 RendererFogEnd = DEFAULT_FOG_END;

    D3DCMPFUNC RendererDepthFunction = D3DCMP_LESSEQUAL;
    D3DCMPFUNC RendererAlphaFunction = D3DCMP_GREATER;
    u32 VertexStreamStride = sizeof(RTLVX);
    u32 MaxRendererSimultaneousTextures = MIN_SIMULTANEOUS_TEXTURE_COUNT;
    u32 RendererVersion = RENDERER_MODULE_VERSION_115;

    u32 RendererIndexSize = RENDERER_MODULE_INDEX_SIZE_4;

    u32 RendererShadeMode = RENDERER_MODULE_SHADE_GOURAUD;
    u32 RendererClearColor = GRAPCHICS_COLOR_WHITE;
    BOOL RendererToggleState = TRUE;

    BOOL IsRendererInit = TRUE;
    u32 RendererVertexSize = sizeof(RTLVX);
    u32 RendererCurrentShader = D3DFVF_TEX1 | D3DFVF_SPECULAR | D3DFVF_DIFFUSE | D3DFVF_XYZRHW;
    f32 RendererClearDepth = CLEAR_DEPTH_VALUE;

    u8 RendererFogAlphas[MAX_OUTPUT_FOG_ALPHA_COUNT];

    RendererModuleDescriptor2 ModuleDescriptor;
    RendererModuleDescriptorDeviceCapabilities ModuleDescriptorDeviceCapabilities[MAX_DEVICE_CAPABILITIES_COUNT];

    s32 RendererTextureFormatStates[MAX_USABLE_TEXTURE_FORMAT_COUNT] =
    {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    }; // TODO

    RendererModule::MinMax MinMax[6] =
    {
        { 0x0,   0x4a },
        { 0x64,  0x6e },
        { 0xc8,  0xd7 },
        { 0x12c, 0x13b },
        { 0x190, 0x19f },
        { 0x2bc, 0x2cb }
    }; // TODO

    s32 UnknownArray06[MAX_ACTIVE_UNKNOWN_COUNT] =
    {
        0, 0, 0, 0, 4, 0, 0, 0, 0, 0
    }; // TODO

    BOOL IsRendererToggleLambdaActive = TRUE;

    u32 PixelFormatSizes[MAX_USABLE_TEXTURE_FORMAT_INDEX_COUNT] =
    {
        0, 1, 1, 2, 2, 3, 4, 2, 1, 2, 2, 2, 8, 16, 16, 0, 0, 0, 0, 2, 3, 0, 0, 2, 4, 2, 4, 2, 4, 4, 0, 0, 0, 0
    }; // Size in Bytes

    BOOL IsTexturePaletteInactive = TRUE;

    ImageFormatDescriptor ImageFormatDescriptors[MAX_IMAGE_FORMAT_DESCRIPTOR_COUNT] =
    {
        { D3DFMT_R8G8B8,    IMAGE_FORMAT_DESCRIPTOR_TYPE_RGB,       GRAPHICS_BITS_PER_PIXEL_24, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_8,  0, 1 },
        { D3DFMT_A8R8G8B8,  IMAGE_FORMAT_DESCRIPTOR_TYPE_RGB,       GRAPHICS_BITS_PER_PIXEL_32, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_8, GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_8,  1, 1 },
        { D3DFMT_X8R8G8B8,  IMAGE_FORMAT_DESCRIPTOR_TYPE_RGB,       GRAPHICS_BITS_PER_PIXEL_32, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_8,  1, 1 },
        { D3DFMT_R5G6B5,    IMAGE_FORMAT_DESCRIPTOR_TYPE_RGB,       GRAPHICS_BITS_PER_PIXEL_16, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_5,  GRAPHICS_BITS_PER_PIXEL_6,  GRAPHICS_BITS_PER_PIXEL_5,  1, 1 },
        { D3DFMT_X1R5G5B5,  IMAGE_FORMAT_DESCRIPTOR_TYPE_RGB,       GRAPHICS_BITS_PER_PIXEL_16, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_5,  GRAPHICS_BITS_PER_PIXEL_5,  GRAPHICS_BITS_PER_PIXEL_5,  1, 1 },
        { D3DFMT_A8P8,      IMAGE_FORMAT_DESCRIPTOR_TYPE_PALETTE,   GRAPHICS_BITS_PER_PIXEL_16, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_8, GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_8,  1, 1 },
        { D3DFMT_P8,        IMAGE_FORMAT_DESCRIPTOR_TYPE_PALETTE,   GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_8, GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_8,  1, 1 },
        { D3DFMT_A1R5G5B5,  IMAGE_FORMAT_DESCRIPTOR_TYPE_RGB,       GRAPHICS_BITS_PER_PIXEL_16, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_1, GRAPHICS_BITS_PER_PIXEL_5,  GRAPHICS_BITS_PER_PIXEL_5,  GRAPHICS_BITS_PER_PIXEL_5,  1, 1 },
        { D3DFMT_A4R4G4B4,  IMAGE_FORMAT_DESCRIPTOR_TYPE_RGB,       GRAPHICS_BITS_PER_PIXEL_16, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_4, GRAPHICS_BITS_PER_PIXEL_4,  GRAPHICS_BITS_PER_PIXEL_4,  GRAPHICS_BITS_PER_PIXEL_4,  1, 1 },
        { D3DFMT_R3G3B2,    IMAGE_FORMAT_DESCRIPTOR_TYPE_RGB,       GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_3,  GRAPHICS_BITS_PER_PIXEL_3,  GRAPHICS_BITS_PER_PIXEL_2,  1, 1 },
        { D3DFMT_A8,        IMAGE_FORMAT_DESCRIPTOR_TYPE_RGB,       GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_8, GRAPHICS_BITS_PER_PIXEL_0,  GRAPHICS_BITS_PER_PIXEL_0,  GRAPHICS_BITS_PER_PIXEL_0,  1, 1 },
        { D3DFMT_A8R3G3B2,  IMAGE_FORMAT_DESCRIPTOR_TYPE_RGB,       GRAPHICS_BITS_PER_PIXEL_16, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_8, GRAPHICS_BITS_PER_PIXEL_3,  GRAPHICS_BITS_PER_PIXEL_3,  GRAPHICS_BITS_PER_PIXEL_2,  1, 1 },
        { D3DFMT_X4R4G4B4,  IMAGE_FORMAT_DESCRIPTOR_TYPE_RGB,       GRAPHICS_BITS_PER_PIXEL_16, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_4,  GRAPHICS_BITS_PER_PIXEL_4,  GRAPHICS_BITS_PER_PIXEL_4,  1, 1 },
        { D3DFMT_L8,        IMAGE_FORMAT_DESCRIPTOR_TYPE_LUMINANCE, GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_8,  1, 1 },
        { D3DFMT_A8L8,      IMAGE_FORMAT_DESCRIPTOR_TYPE_LUMINANCE, GRAPHICS_BITS_PER_PIXEL_16, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_8, GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_8,  1, 1 },
        { D3DFMT_A4L4,      IMAGE_FORMAT_DESCRIPTOR_TYPE_LUMINANCE, GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_4, GRAPHICS_BITS_PER_PIXEL_4,  GRAPHICS_BITS_PER_PIXEL_4,  GRAPHICS_BITS_PER_PIXEL_4,  1, 1 },
        { D3DFMT_V8U8,      IMAGE_FORMAT_DESCRIPTOR_TYPE_UV,        GRAPHICS_BITS_PER_PIXEL_16, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_0,  GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_8,  1, 1 },
        { D3DFMT_L6V5U5,    IMAGE_FORMAT_DESCRIPTOR_TYPE_UV,        GRAPHICS_BITS_PER_PIXEL_16, GRAPHICS_BITS_PER_PIXEL_6, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_0,  GRAPHICS_BITS_PER_PIXEL_5,  GRAPHICS_BITS_PER_PIXEL_5,  1, 1 },
        { D3DFMT_X8L8V8U8,  IMAGE_FORMAT_DESCRIPTOR_TYPE_UV,        GRAPHICS_BITS_PER_PIXEL_32, GRAPHICS_BITS_PER_PIXEL_8, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_0,  GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_8,  1, 1 },
        { D3DFMT_Q8W8V8U8,  IMAGE_FORMAT_DESCRIPTOR_TYPE_UV,        GRAPHICS_BITS_PER_PIXEL_32, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_8, GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_8,  1, 1 },
        { D3DFMT_V16U16,    IMAGE_FORMAT_DESCRIPTOR_TYPE_UV,        GRAPHICS_BITS_PER_PIXEL_32, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_0,  GRAPHICS_BITS_PER_PIXEL_16, GRAPHICS_BITS_PER_PIXEL_16, 1, 1 },
        { D3DFMT_W11V11U10, IMAGE_FORMAT_DESCRIPTOR_TYPE_UV,        GRAPHICS_BITS_PER_PIXEL_32, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_11, GRAPHICS_BITS_PER_PIXEL_11, GRAPHICS_BITS_PER_PIXEL_10, 1, 1 },
        { D3DFMT_UYVY,      IMAGE_FORMAT_DESCRIPTOR_TYPE_RGB,       GRAPHICS_BITS_PER_PIXEL_16, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_8,  0, 1 },
        { D3DFMT_YUY2,      IMAGE_FORMAT_DESCRIPTOR_TYPE_RGB,       GRAPHICS_BITS_PER_PIXEL_16, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_8,  0, 1 },
        { D3DFMT_DXT1,      IMAGE_FORMAT_DESCRIPTOR_TYPE_RGB,       GRAPHICS_BITS_PER_PIXEL_16, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_1, GRAPHICS_BITS_PER_PIXEL_5,  GRAPHICS_BITS_PER_PIXEL_6,  GRAPHICS_BITS_PER_PIXEL_5,  0, 1 },
        { D3DFMT_DXT2,      IMAGE_FORMAT_DESCRIPTOR_TYPE_RGB,       GRAPHICS_BITS_PER_PIXEL_16, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_4, GRAPHICS_BITS_PER_PIXEL_5,  GRAPHICS_BITS_PER_PIXEL_6,  GRAPHICS_BITS_PER_PIXEL_5,  0, 1 },
        { D3DFMT_DXT3,      IMAGE_FORMAT_DESCRIPTOR_TYPE_RGB,       GRAPHICS_BITS_PER_PIXEL_16, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_4, GRAPHICS_BITS_PER_PIXEL_5,  GRAPHICS_BITS_PER_PIXEL_6,  GRAPHICS_BITS_PER_PIXEL_5,  0, 1 },
        { D3DFMT_DXT4,      IMAGE_FORMAT_DESCRIPTOR_TYPE_RGB,       GRAPHICS_BITS_PER_PIXEL_16, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_3, GRAPHICS_BITS_PER_PIXEL_5,  GRAPHICS_BITS_PER_PIXEL_6,  GRAPHICS_BITS_PER_PIXEL_5,  0, 1 },
        { D3DFMT_DXT5,      IMAGE_FORMAT_DESCRIPTOR_TYPE_RGB,       GRAPHICS_BITS_PER_PIXEL_16, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_3, GRAPHICS_BITS_PER_PIXEL_5,  GRAPHICS_BITS_PER_PIXEL_6,  GRAPHICS_BITS_PER_PIXEL_5,  0, 1 },
        { D3DFMT_UNKNOWN,   IMAGE_FORMAT_DESCRIPTOR_TYPE_RGB,       GRAPHICS_BITS_PER_PIXEL_32, GRAPHICS_BITS_PER_PIXEL_0, GRAPHICS_BITS_PER_PIXEL_8, GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_8,  GRAPHICS_BITS_PER_PIXEL_8,  0, 1 }
    };

    u32 TexturePaletteIndexes[MAX_TEXTURE_PALETTE_INDEX_COUNT];
    u32 TexturePaletteValues[MAX_TEXTURE_PALETTE_INDEX_COUNT];
}
